### ISSUE TITLE
Notice: Undefined index: signed_in

### ISSUE THREAD

**Issue by sander1095** [marcokstephen/internet-forum#2]
Hello!

I just read your tutorial and I think it is brilliant! However, when I set it up I got the following error:  
Notice: Undefined index: signed_in in _path_/header.php on line 43

```
if($_SESSION['signed_in'])
{
```

Notice: Undefined index: signed_in in _path_/header.php on line 43

```
if ($_SESSION['user_level'] > 3)
{
```

I've hidden the path for security reasons. I checked the header.php file and the session is getting started, so that is not the issue. I am not a PHP Guru and I can't find the problem, could you tell me what is going on and how I could fix it?

**Comment by marcokstephen** [comment]
Hi there,

It looks like you're getting a notice (not an error) from PHP which usually isn't shown by default. The error is stating that `signed_in` has not yet been declared within the `$_SESSION` array. I highly recommend reading [this StackOverflow answer](http://stackoverflow.com/a/12770836/3358186) to get the most detailed answer about what exactly is happening.

Meanwhile, you should be able to avoid the error by doing the following (and doing the same thing for `user_level` as you also showed in your post):

```
$signedin = array_key_exists('signed_in', $_SESSION) ? $_SESSION['signed_in'] : FALSE;
if($signedin)
{
    ...
}
```

What this does is check to see if `signed_in` has been declared before attempting to use it.
